databases:
  - name: budget
    databaseName: budget_n6ae
    user: budget_n6ae_user

services:
  - type: web
    name: penny-wise
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budget_n6ae
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false