databases:
  - name: pennyapp
    databaseName: pennyapp
    user: pennyapp_user

services:
  - type: web
    name: mysite
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: postgres://pennyapp_user:4URrmOuwX23LPyIbytYDmwPiZ1YOt31V@dpg-ck7pevo8elhc73c384h0-a/pennyapp
        fromDatabase:
          name: pennyapp
          property: connectionString
      - key: f59de52f780884e2992da0fefface473
        sync: false